# wrangler.toml
name = 'matt-hall-portfolio'

compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npx @cloudflare/next-on-pages@latest"
pages_build_output_dir = ".vercel/output/static"

# Optionally, define env vars for local pages dev
[vars]
NEXT_PUBLIC_UMAMI_SRC = "https://umami.slightlybetter.dev/fetch.js"
NEXT_PUBLIC_UMAMI_WEBSITE_ID = "0026123c-1418-4a9c-b43c-5b78386a1597"
