# wrangler.toml
name = 'matt-hall-portfolio'

# Deploy Next.js to Cloudflare Pages using next-on-pages output
pages_build_output_dir = ".vercel/output"

# Use Pages deployments (wrangler pages ...) so account/project is picked at deploy time
# compatibility_date is not required for Pages static/function routing when using next-on-pages

# Optionally, define env vars for local pages dev
[vars]
NEXT_PUBLIC_UMAMI_SRC = "https://umami.slightlybetter.dev/fetch.js"
NEXT_PUBLIC_UMAMI_WEBSITE_ID = "0026123c-1418-4a9c-b43c-5b78386a1597"
